# Generated by Django 5.0.6 on 2024-06-07 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furst_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('appointment', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('workexperience', models.CharField(max_length=3)),
                ('dateofbirth', models.DateField(max_length=12)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('maritalstatus', models.CharField(max_length=15)),
                ('accountnumber', models.CharField(max_length=50)),
                ('bloodtype', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furst_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField(max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furst_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dateofbirth', models.DateField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('addmission', models.CharField(max_length=40)),
                ('discharge', models.CharField(max_length=40)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=40)),
                ('bloodtype', models.CharField(max_length=3)),
                ('martialstatus', models.CharField(max_length=10)),
                ('weight', models.IntegerField(max_length=3)),
                ('height', models.FloatField(max_length=4)),
                ('attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.attachment')),
                ('diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.diagnosis')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.doctor')),
                ('perscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.medication')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.room')),
                ('symptoms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.symptom')),
            ],
        ),
    ]
