# Generated by Django 5.0.6 on 2024-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0002_appointment_remove_doctor_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='bloodtype',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='maritalstatus',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='workexperience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='bank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_appointment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dateofbirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='dateofbirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
