# Generated by Django 5.0.6 on 2024-06-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0003_rename_contact_doctor_phone_remove_doctor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dateofbirth',
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
