# Generated by Django 5.0.6 on 2024-06-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_remove_doctor_dateofbirth_doctor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('F', 'Female')], max_length=5),
        ),
    ]
