# Generated by Django 5.0.6 on 2024-06-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0006_alter_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='addmission',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharge',
            field=models.DateField(),
        ),
    ]
