# Generated by Django 5.0.6 on 2024-06-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0007_alter_patient_addmission_alter_patient_discharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='martialstatus',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='perscription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7),
        ),
    ]
