# Generated by Django 5.0.6 on 2024-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0008_remove_patient_address_remove_patient_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='discharge',
            field=models.DateField(null=True),
        ),
    ]
