# Generated by Django 5.0.6 on 2024-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0009_alter_patient_discharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
