# Generated by Django 5.0.6 on 2024-06-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0011_remove_patient_discharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='addmission',
            new_name='admission',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='furst_name',
            new_name='first_name',
        ),
    ]
