# Generated by Django 5.0.6 on 2024-06-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0013_remove_doctor_bank_patient_age_alter_doctor_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
