# Generated by Django 5.0.6 on 2024-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0014_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
