# Generated by Django 5.0.6 on 2024-06-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0016_patient_roomnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bank',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
