# Generated by Django 5.0.6 on 2024-06-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0017_doctor_bank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
