# Generated by Django 5.0.6 on 2024-06-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0023_alter_doctor_date_of_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_of_appointment',
            field=models.DateField(),
        ),
    ]
